Longest substring without repeating chars, Window Functions in SQL, work with date module in python, multiple ways for creating array using numpy

In [ ]:
# Longest substring without repeating chars
strr='abcabcbb'
l=0
lengh=len(strr)


In [ ]:
# work with date module in python
from datetime import date,datetime,timedelta


In [ ]:
today=date.today()
print(today)
now=datetime.now()
print(now)
mybday=date(2004,11,14)
print(mybday)
future = today + timedelta(days=10)
print(future)
past = today - timedelta(days=5)
print(past)


2025-10-07
2025-10-07 08:21:39.165443
2004-11-14
2025-10-17
2025-10-02


In [ ]:
print(now.minute)
print(now.hour)
print(now.day)
print(now.month)
print(now.year)

21
8
7
10
2025


In [ ]:
# formatted
formetted=now.strftime("%d-%m-%y %H-%M-%S")
print(formetted)

07-10-25 08-21-39


In [3]:
# multiple ways for creating array using numpy
import numpy as np
arr1=np.array([1,2,3,6,5,6]) #1D
arr2=np.array([[12,33],[23,42]])#2D
arr3=np.array(((1,2,3),(4,5,6)))#from tuple

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full((2, 3), 7)


In [ ]:
#identity matrix
np.eye(3)

In [5]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [7]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [8]:
np.random.rand(2, 3)     # uniform 0-1 randoms
np.random.randn(3, 3)    # normal distribution (mean=0, sd=1)
np.random.randint(1, 10, (2, 3))  # random integers


array([[9, 7, 4],
       [3, 1, 9]])